## MySQL ???? ??
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
## DB Source URL
#spring.datasource.url=jdbc:mysql://localhost:3305/test2?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
##DB Username
#spring.datasource.username=tnlvkf12
##DB Password
#spring.datasource.password=gudrhs11
## JPA??? ????
#spring.jpa.show-sql=true
## DDL(create, alter, drop) ??? DB? ?? ??? ??? ? ??.
#spring.jpa.hibernate.ddl-auto=none
## JPA? ???? Hibernate? ????? ??? SQL? ???? ????.
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.open-in-view=false

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: tnlvkf12
    url: jdbc:mysql://localhost:3306/test1?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    password: gudrhs11
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
#    show-sql: true
    hibernate:
      ddl-auto: create

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace


